# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8slivenessprobe
spec:
  crd:
    spec:
      names:
        kind: K8sLivenessProbe
      validation:
        openAPIV3Schema:
          properties:
            excludeIstio:
              type: boolean # Default is false
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8slivenessprobe
        is_create_update_or_audit {
            operation := input.review.operation
            any([ operation == "CREATE", operation == "UPDATE" ])
            operation != "DELETE"
        }
        is_create_update_or_audit {
            # When the constraint is run by the audit process input.review is not set
            input.review.operation == ""
        }
        violation[{"msg": msg}] {
            containers := input.review.object.spec.template.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            is_create_update_or_audit
            not containers.livenessProbe
            not input.parameters.excludeIstio
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a livenessProbe", [kind, name])
        }
        violation[{"msg": msg}] {
            containers := input.review.object.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.livenessProbe
            not input.parameters.excludeIstio
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a livenessProbe", [kind, name])
        }
        violation[{"msg": msg}] {
            containers := input.review.object.spec.jobTemplate.spec.template.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.livenessProbe
            not input.parameters.excludeIstio
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a livenessProbe", [kind, name])
        }

        violation[{"msg": msg}] {
            containers := input.review.object.spec.template.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.livenessProbe
            input.parameters.excludeIstio
            not istio(containers.image)
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a livenessProbe", [kind, name])
        }

        violation[{"msg": msg}] {
            containers := input.review.object.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.livenessProbe
            input.parameters.excludeIstio
            not istio(containers.image)
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a livenessProbe", [kind, name])
        }

        violation[{"msg": msg}] {
            containers := input.review.object.spec.jobTemplate.spec.template.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.livenessProbe
            input.parameters.excludeIstio
            not istio(containers.image)
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a livenessProbe", [kind, name])
        }

        istio(image) {
          contains(image, "istio/proxyv2")
        }
