# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sreadinessprobe
  annotations:
    description: >-
      Requires containers to have a Readiness Probe defined.
      https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
spec:
  crd:
    spec:
      names:
        kind: K8sReadinessProbe
      validation:
        openAPIV3Schema:
          type: object
          properties:
            excludeIstio:
              type: boolean # Default is false
              description: >-
                Setting this parameter to true will make the rule except containers that use Istio image. Otherwise,
                when using Isito the pods will be rejected because the sidecar injected does not comply with the liveness
                probe requirement.
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sreadinessprobe
        is_create_update_or_audit {
            operation := input.review.operation
            any([ operation == "CREATE", operation == "UPDATE" ])
            operation != "DELETE"
        }
        is_create_update_or_audit {
            # When the constraint is run by the audit process input.review is not set
            input.review.operation == ""
        }
        violation[{"msg": msg}] {
            containers := input.review.object.spec.template.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.readinessProbe
            not input.parameters.excludeIstio
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a readinessProbe", [kind, name])
        }
        violation[{"msg": msg}] {
            containers := input.review.object.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.readinessProbe
            not input.parameters.excludeIstio
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a readinessProbe", [kind, name])
        }
        violation[{"msg": msg}] {
            containers := input.review.object.spec.jobTemplate.spec.template.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.readinessProbe
            not input.parameters.excludeIstio
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a readinessProbe", [kind, name])
        }

        violation[{"msg": msg}] {
            containers := input.review.object.spec.template.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.readinessProbe
            input.parameters.excludeIstio
            not istio(containers.image)
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a readinessProbe", [kind, name])
        }
        violation[{"msg": msg}] {
            containers := input.review.object.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.readinessProbe
            input.parameters.excludeIstio
            not istio(containers.image)
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a readinessProbe", [kind, name])
        }
        violation[{"msg": msg}] {
            containers := input.review.object.spec.jobTemplate.spec.template.spec.containers[_]
            name := input.review.object.metadata.name
            kind := input.review.kind.kind
            not containers.readinessProbe
            input.parameters.excludeIstio
            not istio(containers.image)
            is_create_update_or_audit
            msg = sprintf("Rejecting \"%v/%v\" for not specifying a readinessProbe", [kind, name])
        }

        istio(image) {
          contains(image, "istio/proxyv2")
        }
