{
 "title": "Gatekeeper",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "POD",
    "query": {
     "query": "label_values(gatekeeper_constraints, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gatekeeper Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gatekeeper_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gatekeeper_request_count{pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Audit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatekeeper_audit_last_run_time{pod=~\"$pod\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Violations in DENY",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatekeeper_violations{enforcement_action=\"deny\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Violations in DRYRUN",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatekeeper_violations{enforcement_action=\"dryrun\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Violations in UNRECOGNIZED",
   "type": "stat",
   "description": "Violations in Unrecognized enforcement action",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatekeeper_violations{enforcement_action=\"unrecognized\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Constraints (Active)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatekeeper_constraints{status=\"active\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} [{{enforcement_action}}]"
    }
   ]
  },
  {
   "title": "Constraints (Error)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatekeeper_constraints{status=\"error\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} [{{enforcement_action}}]"
    }
   ]
  },
  {
   "title": "Constraint Templates (Active)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatekeeper_constraint_templates{status=\"active\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Constraint Templates (Error)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatekeeper_constraint_templates{status=\"error\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Constraint Templates Ingestion Count",
   "type": "graph",
   "description": "Constraint Templates Ingestion Count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gatekeeper_constraint_template_ingestion_count{pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Webhooks Fail open count",
   "type": "timeseries",
   "description": "Shows the rate of failures for Gatekeeper's webhooks in Fail open (Ignore) mode.\nHaving failures > 0 here indicates that requests are not being evaluated by Gatekeeper's webhook.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(apiserver_admission_webhook_fail_open_count{name=~\".*.gatekeeper.sh\"}[5m])"
    }
   ]
  },
  {
   "title": "Webhooks Fail count",
   "type": "timeseries",
   "description": "Shows the rate of failures for Gatekeeper's webhooks in Fail mode.\nHaving failures > 0 here will make the API server reject all the requests that arrive at it.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(apiserver_admission_webhook_rejection_count{name=~\".*.gatekeeper.sh\"}[5m])"
    }
   ]
  }
 ]
}