# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system

resources:
  - service-monitor.yml
  - alert-rules.yaml

generatorOptions:
  labels:
    grafana-sighup-dashboard: default
  annotations:
    grafana-folder: "OPA"
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-dashboard-definitions-gatekeeper
    files:
      - gatekeeper-dashboard.json
