---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system

resources:
  - service-monitor.yml

generatorOptions:
  labels:
    grafana-sighup-dashboard: default
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-dashboard-definitions-gatekeeper
    files:
      - gatekeeper-dashboard.json