apiVersion: batch/v1
kind: Job
metadata:
  name: kyverno-scale-to-zero
  namespace: kyverno
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.3.7
spec:
  backoffLimit: 2
  template:
    metadata:
    spec:
      serviceAccount: kyverno-admission-controller
      restartPolicy: Never
      containers:
        - name: kubectl
          image: "registry.sighup.io/fury/bitnami/kubectl:1.30.2"
          command:
            - /bin/bash
            - '-c'
            - |-
              set -euo pipefail
              kubectl scale -n kyverno deployment -l app.kubernetes.io/part-of=kyverno --replicas=0
              sleep 30
              kubectl delete validatingwebhookconfiguration -l webhook.kyverno.io/managed-by=kyverno
              kubectl delete mutatingwebhookconfiguration -l webhook.kyverno.io/managed-by=kyverno
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
